baseURL = 'https://tech-scribe.netlify.app/'
languageCode = 'en-uk'
title = 'Tech Scribe'
theme = 'ananke'

menu = ['main', 'footer']

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Content Design blahblahblah"
  background_color_class = "bg-navy"
  recent_posts_number = 4

[[params.ananke_socials]]
name = "github"
url = "https://github.com/ankakulka"
label = "TND GitHub Account"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/anka-kulczycka/"
label = "TND LinkedIn Account"

[[params.ananke_socials]]
name = "behance"
url = "https://www.behance.net/annakul"
label = "TND Behance Account"
color = "#6cc644"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'


